### ISSUE TITLE
Small Issue in "PRHEX"-Routine

### ISSUE THREAD

**Issue by ttahsin-bey** [fishhack66/PAL-1-Stuff#2]
https://github.com/fishhack66/PAL-1-Stuff/blob/aa4b894b9535507d67472e8d8c25ac53fc0ac9d2/Testing/Source%20Files/eWoz_Lite.asm#L245

I think this should be changed to "ORA #$30" in order to get a printable ASCII-Character...

**Comment by fishhack66** [comment]
Agree.  I think it was a mistake - the PAL-1 version of the original eWoz comments here say "Add a '0' "  And I simply put in a #$00 instead of the character ($30).  Fixed. Nice catch!
